### ISSUE TITLE
Request: Patches that have been "Checked" marked different than Completed

### ISSUE THREAD

**Issue by DivineInsanity** [wouterrutgers/farming-guild-overview#1]
Love the plugin and the idea behind it! But i really wanted it so that at a glance I could know what patches need to be reset to be "pre-planted" for Farming Contracts.

I just check-healthed my Potato Cactus and it doesnt change in the plugin until I pick all the cactus and remove it. Could there be a status for patches with a "Check Health" to be like "Checked" or something?

**Comment by wouterrutgers** [comment]
Sure! I'll see if I can update it during the week, otherwise I'll update it next weekend.

Until then, make sure to empty your patches immediately ;-)

**Comment by wouterrutgers** [comment]
I've updated the plugin to include the "Checked" state. You can also pick your own colors when runelite has approved the changes to the plugin.

https://github.com/runelite/plugin-hub/pull/6869 when this is merged you can use the updated plugin!
